# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ai(object):
    def setupUi(self, ai):
        ai.setObjectName("ai")
        ai.resize(816, 712)
        self.TextEdit = TextEdit(ai)
        self.TextEdit.setGeometry(QtCore.QRect(0, 0, 811, 548))
        self.TextEdit.setObjectName("TextEdit")
        self.TextEdit_2 = TextEdit(ai)
        self.TextEdit_2.setGeometry(QtCore.QRect(0, 550, 811, 121))
        self.TextEdit_2.setObjectName("TextEdit_2")
        self.SwitchButton = SwitchButton(ai)
        self.SwitchButton.setGeometry(QtCore.QRect(20, 681, 125, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.SwitchButton.setFont(font)
        self.SwitchButton.setObjectName("SwitchButton")
        self.PushButton = PushButton(ai)
        self.PushButton.setGeometry(QtCore.QRect(680, 676, 131, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PushButton.setIcon(icon)
        self.PushButton.setProperty("hasIcon", True)
        self.PushButton.setObjectName("PushButton")
        self.DropDownToolButton = DropDownToolButton(ai)
        self.DropDownToolButton.setGeometry(QtCore.QRect(160, 676, 57, 32))
        self.DropDownToolButton.setText("")
        self.DropDownToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.DropDownToolButton.setObjectName("DropDownToolButton")

        self.retranslateUi(ai)
        QtCore.QMetaObject.connectSlotsByName(ai)

    def retranslateUi(self, ai):
        _translate = QtCore.QCoreApplication.translate
        ai.setWindowTitle(_translate("ai", "Form"))
        self.SwitchButton.setOnText(_translate("ai", "深度思考r1"))
        self.SwitchButton.setOffText(_translate("ai", "深度思考r1"))
        self.PushButton.setText(_translate("ai", "发送"))
from qfluentwidgets import DropDownToolButton, PushButton, SwitchButton, TextEdit
