# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 710)
        self.TableWidget = TableWidget(Form)
        self.TableWidget.setGeometry(QtCore.QRect(60, 90, 411, 231))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.TitleLabel = TitleLabel(Form)
        self.TitleLabel.setGeometry(QtCore.QRect(60, 40, 124, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.TitleLabel_2 = TitleLabel(Form)
        self.TitleLabel_2.setGeometry(QtCore.QRect(60, 330, 124, 38))
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.TableWidget_2 = TableWidget(Form)
        self.TableWidget_2.setGeometry(QtCore.QRect(60, 370, 411, 231))
        self.TableWidget_2.setObjectName("TableWidget_2")
        self.TableWidget_2.setColumnCount(0)
        self.TableWidget_2.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "data"))
        self.TitleLabel_2.setText(_translate("Form", "book"))
from qfluentwidgets import TableWidget, TitleLabel
