# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'End.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_End(object):
    def setupUi(self, End):
        End.setObjectName("End")
        End.resize(816, 710)
        self.ProgressBar = ProgressBar(End)
        self.ProgressBar.setGeometry(QtCore.QRect(90, 30, 631, 4))
        self.ProgressBar.setProperty("value", 100)
        self.ProgressBar.setObjectName("ProgressBar")
        self.ProgressRing = ProgressRing(End)
        self.ProgressRing.setGeometry(QtCore.QRect(90, 170, 100, 100))
        self.ProgressRing.setProperty("value", 75)
        self.ProgressRing.setVal(75.0)
        self.ProgressRing.setObjectName("ProgressRing")
        self.LargeTitleLabel = LargeTitleLabel(End)
        self.LargeTitleLabel.setGeometry(QtCore.QRect(220, 60, 421, 54))
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.PrimaryPushButton = PrimaryPushButton(End)
        self.PrimaryPushButton.setGeometry(QtCore.QRect(640, 660, 153, 32))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.TitleLabel_2 = TitleLabel(End)
        self.TitleLabel_2.setGeometry(QtCore.QRect(300, 207, 124, 38))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel_2.setFont(font)
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.HyperlinkLabel = HyperlinkLabel(End)
        self.HyperlinkLabel.setGeometry(QtCore.QRect(400, 210, 92, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.HyperlinkLabel.setFont(font)
        self.HyperlinkLabel.setObjectName("HyperlinkLabel")
        self.HorizontalFlipView = HorizontalFlipView(End)
        self.HorizontalFlipView.setGeometry(QtCore.QRect(100, 310, 621, 321))
        self.HorizontalFlipView.setObjectName("HorizontalFlipView")

        self.retranslateUi(End)
        QtCore.QMetaObject.connectSlotsByName(End)

    def retranslateUi(self, End):
        _translate = QtCore.QCoreApplication.translate
        End.setWindowTitle(_translate("End", "Form"))
        self.LargeTitleLabel.setText(_translate("End", "Training is complete"))
        self.PrimaryPushButton.setText(_translate("End", "Continue"))
        self.TitleLabel_2.setText(_translate("End", "正确率："))
        self.HyperlinkLabel.setText(_translate("End", "100%"))
from qfluentwidgets import HorizontalFlipView, HyperlinkLabel, LargeTitleLabel, PrimaryPushButton, ProgressBar, ProgressRing, TitleLabel
