# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home_widget(object):
    def setupUi(self, home_widget):
        home_widget.setObjectName("home_widget")
        home_widget.resize(816, 712)
        self.ProgressBar = ProgressBar(home_widget)
        self.ProgressBar.setGeometry(QtCore.QRect(80, 60, 571, 4))
        self.ProgressBar.setObjectName("ProgressBar")
        self.StrongBodyLabel = StrongBodyLabel(home_widget)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(600, 70, 91, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.HyperlinkLabel = HyperlinkLabel(home_widget)
        self.HyperlinkLabel.setGeometry(QtCore.QRect(580, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.HyperlinkLabel.setFont(font)
        self.HyperlinkLabel.setObjectName("HyperlinkLabel")
        self.StrongBodyLabel_2 = StrongBodyLabel(home_widget)
        self.StrongBodyLabel_2.setGeometry(QtCore.QRect(80, 90, 211, 19))
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.SubtitleLabel = SubtitleLabel(home_widget)
        self.SubtitleLabel.setGeometry(QtCore.QRect(80, 120, 201, 27))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.HorizontalFlipView = HorizontalFlipView(home_widget)
        self.HorizontalFlipView.setGeometry(QtCore.QRect(80, 380, 561, 270))
        self.HorizontalFlipView.setObjectName("HorizontalFlipView")
        self.StrongBodyLabel_3 = StrongBodyLabel(home_widget)
        self.StrongBodyLabel_3.setGeometry(QtCore.QRect(530, 190, 141, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.StrongBodyLabel_3.setFont(font)
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.HyperlinkLabel_2 = HyperlinkLabel(home_widget)
        self.HyperlinkLabel_2.setGeometry(QtCore.QRect(560, 240, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.HyperlinkLabel_2.setFont(font)
        self.HyperlinkLabel_2.setObjectName("HyperlinkLabel_2")
        self.SmoothScrollArea = SmoothScrollArea(home_widget)
        self.SmoothScrollArea.setGeometry(QtCore.QRect(80, 160, 431, 201))
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 429, 199))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.ToolButton = ToolButton(home_widget)
        self.ToolButton.setGeometry(QtCore.QRect(670, 50, 38, 32))
        self.ToolButton.setObjectName("ToolButton")

        self.retranslateUi(home_widget)
        QtCore.QMetaObject.connectSlotsByName(home_widget)

    def retranslateUi(self, home_widget):
        _translate = QtCore.QCoreApplication.translate
        home_widget.setWindowTitle(_translate("home_widget", "Form"))
        self.StrongBodyLabel.setText(_translate("home_widget", "0/30000"))
        self.HyperlinkLabel.setText(_translate("home_widget", "x1.25"))
        self.StrongBodyLabel_2.setText(_translate("home_widget", "今天是2025年5月30日，星期六"))
        self.SubtitleLabel.setText(_translate("home_widget", "您已连续坚持20天"))
        self.StrongBodyLabel_3.setText(_translate("home_widget", "今日已背单词："))
        self.HyperlinkLabel_2.setText(_translate("home_widget", "128个"))
from qfluentwidgets import HorizontalFlipView, HyperlinkLabel, ProgressBar, SmoothScrollArea, StrongBodyLabel, SubtitleLabel, ToolButton
