# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\chengshe\VocabSlayer_update\client\question.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fanyi(object):
    def setupUi(self, fanyi):
        fanyi.setObjectName("fanyi")
        fanyi.resize(745, 678)
        self.PrimaryPushButton = PrimaryPushButton(fanyi)
        self.PrimaryPushButton.setGeometry(QtCore.QRect(280, 530, 121, 31))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.CaptionLabel = CaptionLabel(fanyi)
        self.CaptionLabel.setGeometry(QtCore.QRect(100, 160, 541, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.CaptionLabel.setFont(font)
        self.CaptionLabel.setWordWrap(True)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.layoutWidget = QtWidgets.QWidget(fanyi)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 300, 561, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RadioButton = RadioButton(self.layoutWidget)
        self.RadioButton.setObjectName("RadioButton")
        self.verticalLayout.addWidget(self.RadioButton)
        self.RadioButton_2 = RadioButton(self.layoutWidget)
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.verticalLayout.addWidget(self.RadioButton_2)
        self.RadioButton_3 = RadioButton(self.layoutWidget)
        self.RadioButton_3.setObjectName("RadioButton_3")
        self.verticalLayout.addWidget(self.RadioButton_3)
        self.LargeTitleLabel = LargeTitleLabel(fanyi)
        self.LargeTitleLabel.setGeometry(QtCore.QRect(40, 50, 531, 54))
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.BodyLabel = BodyLabel(fanyi)
        self.BodyLabel.setGeometry(QtCore.QRect(100, 120, 411, 19))
        self.BodyLabel.setObjectName("BodyLabel")

        self.retranslateUi(fanyi)
        QtCore.QMetaObject.connectSlotsByName(fanyi)

    def retranslateUi(self, fanyi):
        _translate = QtCore.QCoreApplication.translate
        fanyi.setWindowTitle(_translate("fanyi", "Form"))
        self.PrimaryPushButton.setText(_translate("fanyi", "NEXT"))
        self.CaptionLabel.setText(_translate("fanyi", "Here is a sample question. Select the most appropriate option from the choices to fill in the blank.Here is a sample question. Select the most appropriate option from the choices to fill in the blank.  "))
        self.RadioButton.setText(_translate("fanyi", "Radio button"))
        self.RadioButton_2.setText(_translate("fanyi", "Radio button"))
        self.RadioButton_3.setText(_translate("fanyi", "Radio button"))
        self.LargeTitleLabel.setText(_translate("fanyi", "欢迎使用万识斩,%username"))
        self.BodyLabel.setText(_translate("fanyi", "对应的配置之后可在设置选项中调整"))
from qfluentwidgets import BodyLabel, CaptionLabel, LargeTitleLabel, PrimaryPushButton, RadioButton
