# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quiz(object):
    def setupUi(self, fanyi):
        fanyi.setObjectName("fanyi")
        fanyi.resize(745, 678)
        self.PrimaryPushButton = PrimaryPushButton(fanyi)
        self.PrimaryPushButton.setGeometry(QtCore.QRect(550, 580, 121, 31))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.CaptionLabel = CaptionLabel(fanyi)
        self.CaptionLabel.setGeometry(QtCore.QRect(100, 160, 541, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.CaptionLabel.setFont(font)
        self.CaptionLabel.setWordWrap(True)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.layoutWidget = QtWidgets.QWidget(fanyi)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 300, 561, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RadioButton = RadioButton(self.layoutWidget)
        self.RadioButton.setObjectName("RadioButton")
        self.verticalLayout.addWidget(self.RadioButton)
        self.RadioButton_2 = RadioButton(self.layoutWidget)
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.verticalLayout.addWidget(self.RadioButton_2)
        self.RadioButton_3 = RadioButton(self.layoutWidget)
        self.RadioButton_3.setObjectName("RadioButton_3")
        self.verticalLayout.addWidget(self.RadioButton_3)
        self.RadioButton_4 = RadioButton(self.layoutWidget)
        self.RadioButton_4.setObjectName("RadioButton_4")
        self.verticalLayout.addWidget(self.RadioButton_4)
        self.ProgressBar = ProgressBar(fanyi)
        self.ProgressBar.setGeometry(QtCore.QRect(100, 30, 521, 4))
        self.ProgressBar.setProperty("value", 75)
        self.ProgressBar.setVal(75.0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.ProgressRing = ProgressRing(fanyi)
        self.ProgressRing.setGeometry(QtCore.QRect(520, 50, 100, 100))
        self.ProgressRing.setProperty("value", 100)
        self.ProgressRing.setVal(100.0)
        self.ProgressRing.setObjectName("ProgressRing")
        self.PushButton = PushButton(fanyi)
        self.PushButton.setGeometry(QtCore.QRect(290, 530, 111, 31))
        self.PushButton.setObjectName("PushButton")
        self.SplitToolButton = SplitToolButton(fanyi)
        self.SplitToolButton.setGeometry(QtCore.QRect(660, 20, 69, 32))
        self.SplitToolButton.setObjectName("SplitToolButton")
        self.BodyLabel = BodyLabel(fanyi)
        self.BodyLabel.setGeometry(QtCore.QRect(450, 260, 91, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.BodyLabel.setFont(font)
        self.BodyLabel.setObjectName("BodyLabel")
        self.SubtitleLabel = SubtitleLabel(fanyi)
        self.SubtitleLabel.setGeometry(QtCore.QRect(540, 253, 81, 27))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.BodyLabel_2 = BodyLabel(fanyi)
        self.BodyLabel_2.setGeometry(QtCore.QRect(540, 90, 66, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.BodyLabel_2.setFont(font)
        self.BodyLabel_2.setObjectName("BodyLabel_2")

        self.retranslateUi(fanyi)
        QtCore.QMetaObject.connectSlotsByName(fanyi)

    def retranslateUi(self, fanyi):
        _translate = QtCore.QCoreApplication.translate
        fanyi.setWindowTitle(_translate("fanyi", "Form"))
        self.PrimaryPushButton.setText(_translate("fanyi", "NEXT"))
        self.CaptionLabel.setText(_translate("fanyi", "Here is a sample question. Select the most appropriate option from the choices to fill in the blank.Here is a sample question. Select the most appropriate option from the choices to fill in the blank.  "))
        self.RadioButton.setText(_translate("fanyi", "Radio button"))
        self.RadioButton_2.setText(_translate("fanyi", "Radio button"))
        self.RadioButton_3.setText(_translate("fanyi", "Radio button"))
        self.RadioButton_4.setText(_translate("fanyi", "Radio button"))
        self.PushButton.setText(_translate("fanyi", "Push button"))
        self.BodyLabel.setText(_translate("fanyi", "正确答案为"))
        self.SubtitleLabel.setText(_translate("fanyi", "A"))
        self.BodyLabel_2.setText(_translate("fanyi", "accuracy"))
from qfluentwidgets import BodyLabel, CaptionLabel, PrimaryPushButton, ProgressBar, ProgressRing, PushButton, RadioButton, SplitToolButton, SubtitleLabel
