# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\chengshe\VocabSlayer_update\client\ranking.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 710)
        self.TitleLabel = TitleLabel(Form)
        self.TitleLabel.setGeometry(QtCore.QRect(60, 40, 161, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.TableWidget = TableWidget(Form)
        self.TableWidget.setGeometry(QtCore.QRect(60, 150, 701, 431))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.ComboBox = ComboBox(Form)
        self.ComboBox.setGeometry(QtCore.QRect(60, 90, 161, 32))
        self.ComboBox.setObjectName("ComboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "排行榜"))
from qfluentwidgets import ComboBox, TableWidget, TitleLabel
