# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_ai.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 712)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        Form.setFont(font)
        self.PillPushButton = PillPushButton(Form)
        self.PillPushButton.setGeometry(QtCore.QRect(300, 560, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.PillPushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/deepseek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PillPushButton.setIcon(icon)
        self.PillPushButton.setIconSize(QtCore.QSize(18, 18))
        self.PillPushButton.setObjectName("PillPushButton")
        self.HyperlinkLabel = HyperlinkLabel(Form)
        self.HyperlinkLabel.setGeometry(QtCore.QRect(50, 110, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.HyperlinkLabel.setFont(font)
        self.HyperlinkLabel.setObjectName("HyperlinkLabel")
        self.IndeterminateProgressRing = IndeterminateProgressRing(Form)
        self.IndeterminateProgressRing.setGeometry(QtCore.QRect(480, 340, 80, 80))
        self.IndeterminateProgressRing.setObjectName("IndeterminateProgressRing")
        self.StrongBodyLabel = StrongBodyLabel(Form)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(490, 440, 113, 19))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.StrongBodyLabel.setFont(font)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.PushButton = PushButton(Form)
        self.PushButton.setGeometry(QtCore.QRect(480, 500, 102, 32))
        self.PushButton.setObjectName("PushButton")
        self.TableWidget = TableWidget(Form)
        self.TableWidget.setGeometry(QtCore.QRect(430, 230, 201, 301))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(100, 230, 157, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SpinBox = SpinBox(self.widget)
        self.SpinBox.setProperty("value", 30)
        self.SpinBox.setObjectName("SpinBox")
        self.verticalLayout.addWidget(self.SpinBox)
        self.ComboBox_3 = ComboBox(self.widget)
        self.ComboBox_3.setObjectName("ComboBox_3")
        self.verticalLayout.addWidget(self.ComboBox_3)
        self.ComboBox_4 = ComboBox(self.widget)
        self.ComboBox_4.setObjectName("ComboBox_4")
        self.verticalLayout.addWidget(self.ComboBox_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PillPushButton.setText(_translate("Form", "Let\'s Go"))
        self.HyperlinkLabel.setText(_translate("Form", "  AI training"))
        self.StrongBodyLabel.setText(_translate("Form", "生成中......"))
        self.PushButton.setText(_translate("Form", "生成题单"))
        self.SpinBox.setSuffix(_translate("Form", "题"))
        self.SpinBox.setPrefix(_translate("Form", "题数"))
from qfluentwidgets import ComboBox, HyperlinkLabel, IndeterminateProgressRing, PillPushButton, PushButton, SpinBox, StrongBodyLabel, TableWidget
