# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\chengshe\VocabSlayer_update\client\start_review.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 712)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        Form.setFont(font)
        self.LargeTitleLabel = LargeTitleLabel(Form)
        self.LargeTitleLabel.setGeometry(QtCore.QRect(50, 110, 351, 54))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.LargeTitleLabel.setFont(font)
        self.LargeTitleLabel.setAutoFillBackground(False)
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.PillPushButton = PillPushButton(Form)
        self.PillPushButton.setGeometry(QtCore.QRect(310, 560, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.PillPushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\chengshe\\VocabSlayer_update\\client\\resource/deepseek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PillPushButton.setIcon(icon)
        self.PillPushButton.setIconSize(QtCore.QSize(18, 18))
        self.PillPushButton.setObjectName("PillPushButton")
        self.SpinBox = SpinBox(Form)
        self.SpinBox.setGeometry(QtCore.QRect(300, 370, 155, 33))
        self.SpinBox.setProperty("value", 30)
        self.SpinBox.setObjectName("SpinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LargeTitleLabel.setText(_translate("Form", "review training"))
        self.PillPushButton.setText(_translate("Form", "Let\'s Go"))
        self.SpinBox.setSuffix(_translate("Form", "题"))
        self.SpinBox.setPrefix(_translate("Form", "题数"))
from qfluentwidgets import LargeTitleLabel, PillPushButton, SpinBox
