# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 712)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        Form.setFont(font)
        self.LargeTitleLabel = LargeTitleLabel(Form)
        self.LargeTitleLabel.setGeometry(QtCore.QRect(50, 110, 351, 54))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.LargeTitleLabel.setFont(font)
        self.LargeTitleLabel.setAutoFillBackground(False)
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.PillPushButton = PillPushButton(Form)
        self.PillPushButton.setGeometry(QtCore.QRect(310, 560, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.PillPushButton.setFont(font)
        icon = QtGui.QIcon()
        # 获取 client/resource 目录的 deepseek 图标路径
        client_dir = os.path.dirname(os.path.abspath(__file__))
        deepseek_path = os.path.join(client_dir, "resource", "deepseek.png")
        icon.addPixmap(QtGui.QPixmap(deepseek_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PillPushButton.setIcon(icon)
        self.PillPushButton.setIconSize(QtCore.QSize(18, 18))
        self.PillPushButton.setObjectName("PillPushButton")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 220, 157, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SpinBox = SpinBox(self.layoutWidget)
        self.SpinBox.setProperty("value", 30)
        self.SpinBox.setObjectName("SpinBox")
        self.verticalLayout.addWidget(self.SpinBox)
        self.ComboBox = ComboBox(self.layoutWidget)
        self.ComboBox.setObjectName("ComboBox")
        self.verticalLayout.addWidget(self.ComboBox)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(450, 220, 151, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ComboBox_3 = ComboBox(self.layoutWidget1)
        self.ComboBox_3.setObjectName("ComboBox_3")
        self.verticalLayout_2.addWidget(self.ComboBox_3)
        self.ComboBox_4 = ComboBox(self.layoutWidget1)
        self.ComboBox_4.setObjectName("ComboBox_4")
        self.verticalLayout_2.addWidget(self.ComboBox_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LargeTitleLabel.setText(_translate("Form", "routine training"))
        self.PillPushButton.setText(_translate("Form", "Let\'s Go"))
        self.SpinBox.setSuffix(_translate("Form", "题"))
        self.SpinBox.setPrefix(_translate("Form", "题数"))
from qfluentwidgets import ComboBox, LargeTitleLabel, PillPushButton, SpinBox
